config/routes.rb
Rails.application.routes.draw do
  resources :routes

  get 'home/index'

  devise_for :users
  root to: 'home#index'
  get 'tracks/:id/download' => 'tracks#download', as: :track_download

end

app/models/gpx.rb
class Numeric
  def to_rad
    self * Math::PI / 180
  end
end

class Gpx
  attr_reader :points, :distance, :total_ascent, :total_descent

  def initialize(path)
    @coords        = []
    @elevations    = []
    @distance      = 0
    @total_ascent  = 0
    @total_descent = 0
    load_gpx path
  end

  def load_gpx(path)
    File.open(path) { |file| parse_gpx file }
  end

  def parse_gpx(file)
    gpx   = Nokogiri::XML file
    nodes = gpx.xpath('//xmlns:trkpt')

    nodes.each do |node|
      @coords << [ node['lat'].to_f, node['lon'].to_f ]

      node.children.each do |child|
        @elevations << child.content.to_f if child.node_name == 'ele'
      end
    end

    calc_distance
    calc_elevations
  end

  def calc_distance
    @distance = 0
    i         = 0

    loop do
      a = @coords[ i ]
      b = @coords[ i + 1 ]

      @distance += distance_between_points( a, b )

      i += 1
      break if i >= @coords.length - 2
    end
  end

  def calc_elevations
    @total_ascent, @total_descent = 0, 0
    i = 0
    loop do
      a = @elevations[ i ]
      b = @elevations[ i + 1 ]

      b > a ? @total_ascent += (b - a) : @total_descent += (a - b)
      i += 1
      break if i >= @elevations.length - 2
    end
  end

  # Haversine distance formula from https://gist.github.com/j05h/673425

  def distance_between_points(loc1, loc2)
     lat1, lon1 = loc1
     lat2, lon2 = loc2
     dLat       = (lat2 - lat1).to_rad
     dLon       = (lon2 - lon1).to_rad

     a = Math.sin(dLat/2) * Math.sin(dLat/2) +
         Math.cos(lat1.to_rad) * Math.cos(lat2.to_rad) *
         Math.sin(dLon/2) * Math.sin(dLon/2)

     c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))

     d = 6371 * c
  end
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_one :track, dependent: :destroy
  accepts_nested_attributes_for :track
  validates :title, presence: true
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :route
  has_attached_file :gpx
  validates_attachment_file_name :gpx, :matches => [/gpx\Z/]

  def process_gpx
    gpx = Gpx.new self.gpx.path
    self.update_attributes distance: gpx.distance.round(1),
                           total_ascent: gpx.total_ascent.round,
                           total_descent: gpx.total_descent.round
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route       = Route.new
    @route.track = Track.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)
    respond_to do |format|
      if @route.save
        @route.track.process_gpx
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @route.update(route_params)
        @route.track.process_gpx
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_route
      @route = Route.find(params[:id])
    end

    def route_params
      params.require(:route).permit(
        :title,
        :description,
        :distance,
        :total_ascent,
        track_attributes: [:gpx, :id])
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def download
    track = Track.find params[:id]
    send_file track.gpx.path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/home/index.html.haml
%h1
  Hi there Chiang Mai rider!
%p
  This is a site made for
  %b you.
%p
  Check out the
  = link_to 'routes page', routes_path
  and look for a new ride!

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => 'en'}
  %head
    %meta{ :charset => 'utf-8' }

    %meta{ :name => 'viewport', :content => 'width=device-width, initial-scale=1.0' }

    %title= content_for?(:title) ? yield(:title) : 'CNX biker'

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'vendor/modernizr'
    = csrf_meta_tag

  %body

    = render 'shared/site_navigation'

    = render 'shared/flash'

    = yield

    = javascript_include_tag 'application'

app/views/routes/_form.html.haml
= simple_form_for @route do |r|
  = r.simple_fields_for :track do |t|
    = t.input :gpx
  = r.input :title
  = r.input :description
  = r.button :submit

app/views/routes/edit.html.haml
%h1 Editing route

= render 'form'

= link_to 'Show', @route
\|
= link_to 'Back', routes_path

app/views/routes/index.html.haml
%h1 Listing routes

%table
  %tr
    %th Title
    %th Description
    %th Distance
    %th Total ascent
    %th
    %th
    %th

  - @routes.each do |route|
    %tr
      %td= route.title
      %td= route.description
      %td= route.track.distance
      %td= route.track.total_ascent
      %td= link_to 'Show', route
      %td= link_to 'Edit', edit_route_path(route)
      %td= link_to 'Destroy', route, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Route', new_route_path

app/views/routes/new.html.haml
%h1 New route

= render 'form'

= link_to 'Back', routes_path

app/views/routes/show.html.haml
#map
#text
  .row
    .route-side.small-12.large-4.columns
      %h4.route-title= @route.title

      %ul.inline-list
        %li
          %strong= number_to_human @route.track.distance, units: { unit: 'km' }
          %label Distance
        %li
          %strong= number_to_human @route.track.total_ascent, units: { unit: 'm' }
          %label Total Ascent

      = content_tag 'h6', id: 'track', data: { url: @route.track.gpx.url } do
        = link_to track_download_path(@route.track), { target: '_self' } do
          Download
          = number_to_human_size @route.track.gpx_file_size

    .route-main.small-12.large-offset-1.large-7.columns
      %p= @route.description

%link{href: 'http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css', rel: 'stylesheet'}
%script{src: 'http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js'}

app/views/shared/_flash.html.haml
- flashes = {:notice => 'success', :alert => 'standard', :error => 'alert', :secondary => 'secondary'}
- flashes.each do |key, value|
  - if flash[key]
    .alert-box{:class => value, :data => { :alert => '' } }
      = flash[key]
      = link_to '&times;'.html_safe, '#', :class => 'close'

app/views/shared/_site_navigation.html.haml
%nav.top-bar{"data-topbar" => "", :role => "navigation"}
  %ul.title-area
    %li.name
      %h1
        = link_to 'CNX Biker', root_path
    / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    / Left Nav Section
    %ul.left
      %li
        = link_to 'Routes', routes_path
      %li
        =link_to 'Sign up', new_user_registration_path, class: 'button' unless user_signed_in?
    / Right Nav Section
    %ul.right
      - if user_signed_in?
        %li.has-dropdown
          = link_to current_user.email, '#'
          %ul.dropdown
            %li
              %a{:href => "#"} User settings
            %li
              = link_to 'Sign out', destroy_user_session_path, method: :delete
      - else
        %li
          = link_to 'Sign in', new_user_session_path